Axtell/Axtell

- README.md
- app/server.py
- config.default.py
- debug.sh
- requirements.txt
- setup.sh
- static/scss/content.scss
- static/scss/header.scss
- static/scss/main.scss
- static/scss/nodes.scss
- static/scss/variables.scss
- templates/includes/header.html
- templates/index.html
- templates/layouts/layout.html
- templates/layouts/page.html
- templates/notfound.html
- templates/post.html
This adds some more setup for the CSS and all and also brings a pretty crappy but basic template for putting in frontend stuff. This also adds a `debug.sh` to run flask in debug mode and an interactive `setup.sh` to install + setup MySQL.
> Add new compilation steps for layouts

- .gitignore
- Gemfile
- README.md
- app/server.py
- package.json
- requirements.txt
- setup.sh
- static/scss/header.scss
- static/scss/nodes.scss
- static/scss/variables.scss
This addresses the:
- broken `setup.py`
- uses local instead of global NPM modules to avoid installation nightmares
- more CSS variables for when more things are added
> Fix previous issues

- .travis.yml
- Gemfile
Sets up DB and installs packages
> Add travis

- .gitignore
- app/helpers/markdown/markdown.js
- package.json
- production.sh
- static/scss/body.scss
- static/scss/header/header.scss
- static/scss/nodes.scss
- static/scss/page/post/posts.scss
- static/scss/select-dialog.scss
- templates/includes/header.html
- templates/layouts/page.html
This adds some front-end tweaks but mainly it fixes a bug where rendering node.js process would error.
> Fix markdown rendering bug

- .travis.yml
- app/start.py
- tests/flask/test_static.py
- tests/route_tests/test_static.py
- tests/test_base.py
- tests/user_tests/test_user_api.py
- tests/user_tests/test_user_model.py
This adds unit tests for:
- Static pages
- Error pages
- User API
> Add unit tests

- app/routes/static.py
- static/scss/buttons.scss
- static/scss/content.scss
- static/scss/error-page.scss
- static/scss/header/header.scss
- templates/notfound.html
- templates/servererror.html
Adds a nicer page for internal server errors.
> Add 500 page

- misc/markdown.js
- static/js/helper/ErrorManager.js
- static/js/models/TIO/TIORun.js
- static/js/models/TIO/TIOSerializer.js
- static/js/template/TIO/TIOOutputTemplate.js
- static/js/ui/exec/exec-tio.js
- static/package.json
- static/scss/tio.scss
This adds a '▶ Run' button which will run a program on TIO and show the result.
> Add TIO integration

- debug.sh
- static/scss/page/post/post.scss
Adds `flex: 1` for later create post boxes. I'm not sure if an expanding
box would be helpful so I'm not adding that yet.
Also I removed a thing from debug.sh that I mistakenly commited in the
first place :P
> Make 'create post' form full size

- .gitignore
- misc/esdoc.css
- static/.esdoc.json
- static/js/models/Auth.js
- static/package.json
Self-explanatory. Go to `static` and run `npm run docs` to generate docs (output at `/docs-js/index.html`)
> Add docs for JavaScript

- app/routes/post.py
- misc/markdown.js
- package.json
Does not work yet because of the celery/markdown errors. 
> Add footnotes to markdown

- static/js/controllers/Form/FormController.js
- static/js/controllers/SelectDialogViewController.js
- static/js/controllers/TIOController/TIOExec.js
- static/js/controllers/ViewController.js
- static/js/delegate/ActionControllerDelegate.js
- static/js/models/State.js
- static/js/ui/exec/exec-tio.js
- static/js/ui/views/form.js
- static/js/ui/views/selectDialog.js
- static/js/ui/write/post.js
- templates/post/write.html
Moves/adds some JS functions here and there to make for nicer and more future-proof code.
> Restructure JS

- static/js/controllers/SelectDialogViewController.js
- static/js/delegate/SortControllerDelegate.js
- static/js/main.js
- static/js/ui/views/selectDialog.js
- static/js/ui/write/answer.js
- static/package.json
- static/scss/variables-dark.scss
- templates/layouts/page.html
- templates/posts.html
Adds client-side sorting and also fixes JS issues where it wasn't immediately executed.
> Fix client-side JS + fix sorting

- static/js/delegate/SortControllerDelegate.js
- static/scss/answer/view.scss
- static/scss/page/post/post.scss
- templates/post/view.html
Adds various tweaks for answer views including:
- Pagination for answers
- Frontend for answer sorting
> More Frontend Tweaks

- static/js/ui/index.js
- static/js/ui/nav.js
- static/scss/header/header.scss
- templates/includes/header.html
- templates/includes/header/responsive_nav.html
Hamburger menu opens a nav screen.
> Add navigation for mobile device

- app/helpers/macros/render.py
- app/models/Answer.py
- app/routes/post.py
- config.default.py
- misc/logo-template.svg
- static/js/controllers/LanguageLookupViewController.js
- static/js/models/Answer.js
- static/js/models/Language.js
- static/js/models/User.js
- static/scss/answer/view.scss
- static/scss/body.scss
- static/scss/content.scss
- static/scss/form.scss
- static/scss/header/header.scss
- static/scss/lang.scss
- static/scss/leaderboard.scss
- static/scss/nodes.scss
- static/scss/variables-dark.scss
- static/scss/variables.scss
- templates/includes/answer-box.html
- templates/layouts/layout.html
- templates/post/view.html
- templates/posts.html
This also fixes various alignment bugs and fixes dark mode. Also this now adds a couple SEO-related + Open Graph tags.
> Adds a h*ck ton of css changes

- templates/posts.html
There's no need for the post body to be part of the preview. Styling it like SE would be much cleaner.
Addresses #24
> Better post previews

- static/js/delegate/SortControllerDelegate.js
- static/scss/answer/view.scss
- static/scss/main.scss
- static/scss/nodes.scss
- static/scss/page/post/posts.scss
- static/scss/pagination.scss
- static/scss/userbox.scss
- static/scss/variables-dark.scss
- static/scss/variables.scss
- templates/includes/userbox.html
- templates/post/view.html
- templates/posts.html
Pretty basic. Can obviously add more things when we add them e.g. profile links, rep, etc.
I have not yet thought of a layout for answers
> Add userbox for posts and answers

- app/controllers/answer.py
- static/scss/main.scss
- static/scss/upgrade-browser.scss
- templates/layouts/page.html
We might want to use sessions to track if a user has already seen the dialog.
> Add popup for unsupported browsers

- app/controllers/vote.py
- app/routes/vote.py
- tests/vote_tests/test_vote.py
Frontend still needs to handle self-voting attempts and vote changing correctly (@vihanb)
> Prevent self-voting, return breakdown instead of total on post

- static/js/controllers/SelectDialogViewController.js
- static/js/helper/ErrorManager.js
- static/scss/buttons.scss
- static/scss/main.scss
- static/scss/page/page.scss
- static/scss/select-dialog.scss
- templates/includes/header/authmanager.html
- templates/includes/header/useroverview.html
- templates/layouts/page.html
- templates/layouts/split.html
- templates/post/view.html
- templates/post/write.html
- templates/posts.html
Site isn't very accessible so this adds some accessibility things. 
> Accessibility changes

- app/controllers/vote.py
- app/models/Leaderboard.py
- app/routes/static.py
> Return no vote instead of 403 error for anon users

- app/controllers/vote.py
- app/models/Language.py
- package.json
- static/.babelrc
- static/.esdoc.json
- static/js/controllers/AceViewController.js
- static/js/controllers/AnswerViewController.js
- static/js/controllers/AnswerVoteViewController.js
- static/js/controllers/Form/FormConstraint.js
- static/js/controllers/PostVoteViewController.js
- static/js/controllers/ViewController.js
- static/js/controllers/VoteViewController.js
- static/js/helper/ErrorManager.js
- static/js/models/Auth.js
- static/js/models/Data.js
- static/js/models/Request/AnswerVote.js
- static/js/models/Request/PostVote.js
- static/js/models/Request/Request.js
- static/js/models/Request/Vote.js
- static/js/ui/index.js
- static/js/ui/views/post.js
- static/package.json
- static/scss/body.scss
- static/scss/header/header.scss
- static/scss/vote.scss
- templates/includes/header.html
- templates/post/view.html
CSS tweaks, optimizations, and most importantly voting on posts.
> Post voting

- README.md
- app/routes/auth.py
- config.default.py
- setup.sh
This adds small fixes which caused errors.
> Various fixes

- .travis.yml
- deploy/deploy.bash
- deploy/update.bash
> Adjust perms to hopefully avoid rsync errors.

- static/js/ui/write/answer.js
> Add UTF8 buffer

- static/scss/main.scss
- static/scss/page/user/banner.scss
- static/scss/page/user/user.scss
- static/scss/variables-shared.scss
- templates/user.html
> User profile overhaul

- static/js/controllers/MarkdownControls/MarkdownStrikethroughControl.js
- static/js/controllers/VoteViewController.js
- static/js/main.js
- static/scss/vote.scss
- templates/includes/voting.html
- templates/post/view.html
> Add nice indicators when voting for own post

- config.default.py
- js/controllers/AnswerVoteViewController.js
- js/controllers/PostVoteViewController.js
- js/main.js
- js/models/Analytics.js
- js/ui/login.js
- scss/header/changelog.scss
- templates/includes/header/useropts.html
- templates/includes/header/useroverview.html
- templates/layouts/page.html
This adds a couple of tweaks:
- Removes duplicate 'new feature' indicator.
- Adds some analytics.
- Cache breaker for assets
- Fix the theme by using 'theme' var
> Frontend tweaks

- js/controllers/ProgressButtonController.js
- js/delegate/FormControllerDelegate.js
- js/models/Theme.js
- js/ui/settings/profile.js
Adds loading progress state using `ProgressButtonController` class.
> Add loading for the profile page

- js/controllers/WriteCommentViewController.js
- scss/nodes.scss
Register a comment submission handler using `KeyManager#registerMeta`.
> Add Ctrl+Enter to submit comments.

- .travis.yml
- app/server.py
- config.default.py
- requirements.txt
- setup.sh
- templates/layouts/page.html
Adds seperate backend/frontend bugsnags, also disables reporter when bugsnag is not enabled.
> Flask bugsnag

- app/controllers/user.py
- app/models/User.py
- js/models/Auth.js
- js/models/Request/User.js
- js/models/User.js
- js/template/Template.js
- js/template/UserOverviewTemplate.js
- js/ui/index.js
- js/ui/userbox.js
- scss/main.scss
- scss/page/posts.scss
- scss/user-popup.scss
- scss/userbox.scss
- scss/variables-dark.scss
- scss/variables.scss
- templates/includes/userbox.html
- templates/layouts/page.html
- templates/post/view.html
> Design changes

- app/helpers/comments.py
- js/controllers/ModalController.js
- js/controllers/PopoverViewController.js
- js/helpers/ErrorManager.js
- js/models/Analytics.js
- js/template/Template.js
- js/ui/write/answer.js
- scss/popover.scss
This:
- Adds `willUnload`/`didUnload` abstract methods to `Template` class
- Adds load event hooks to `PopoverViewController`
- Modify Bugsnag config
- Add answer events
- Fixed comment loading count bug.
> Change some bugsnag config settings.

- scss/form.scss
- scss/userbox.scss
Fixes contrast issues on dark theme for:
- Timestamps
- User settings > email
- User settings > avatar url
Fixes #88
> Fix contrast issues

- app/controllers/comment.py
> Fix comment counting bug

- app/controllers/post.py
- app/helpers/macros/encode.py
- requirements.txt
- templates/post/view.html
- templates/posts.html
> Add post slugs and updated descriptions

- js/controllers/AnimationController.js
- js/controllers/CommentListViewController.js
- js/controllers/LoadMoreCommentsViewController.js
- js/controllers/PopoverViewController.js
- js/controllers/WriteCommentViewController.js
- js/delegate/AnimationControllerDelegate.js
- js/template/LanguageTemplate.js
- scss/answer/view.scss
- scss/answer/write.scss
- scss/body.scss
- scss/comment.scss
- scss/form.scss
- scss/main.scss
- scss/nodes.scss
- scss/page/posts.scss
- scss/template-animations.scss
- templates/includes/answer-box.html
- templates/includes/comment.html
Adds/changes 5 main things:
- Fix capitalization CSS issue
- Fix JavaScript spacing issue
- Add slide animation for answer box
- Add expand comment animation
- Add 'appendFirst' `enum InstanceType` member so 'loading dialog' positions correctly.
> More modifications

- js/helpers/ErrorManager.js
- js/main.js
- js/models/Auth.js
- js/models/Request/Request.js
So we do a couple things:
- We report errors when loading data to bugsnag
- We report unhandled errors to bugsnag
- We provide an anonymous 'instance id' to bugsnag 
> Add instance id to bugsnag to ID errors

- .babelrc
- deploy/deploy.bash
> Attempt to fix iOS syntax error in JS

- js/ui/write/answer.js
> Keep answer box to avoid bork alert

- scss/answer/write.scss
- scss/auth.scss
- scss/comment.scss
- scss/header/header.scss
- scss/header/help-header.scss
- scss/help-topics.scss
- scss/nodes.scss
- scss/page/posts.scss
- scss/swipe-menu.scss
- scss/variables-dark.scss
- scss/variables.scss
This makes dark theme 100000x better
Before:
After:
> Change shadow-mix on dark-theme to black

- scss/buttons.scss
> Fix alignment of buttons

- app/helpers/macros/__init__.py
- app/helpers/macros/csrf.py
- app/instances/csrf.py
- app/routes/answer.py
- app/routes/comment.py
- app/routes/post.py
- app/routes/user_settings.py
- app/session/__init__.py
- app/session/csrf.py
- app/session/user_session.py
- app/start.py
- js/models/Request/ImgurUpload.js
- js/models/Request/Request.js
- requirements.txt
- templates/includes/answer-box.html
- templates/includes/header/useropts.html
- templates/layouts/page.html
- templates/settings.html
I hope this doesn't wreck the tests
> Add CSRF protection

- js/models/StackExchange.js
- scss/answer/view.scss
- scss/body.scss
- scss/buttons.scss
- scss/form.scss
- scss/nodes.scss
- scss/page/posts.scss
- scss/variables-dark.scss
- scss/variables-shared.scss
- scss/variables.scss
- templates/layouts/page.html
- templates/post/view.html
- templates/posts.html
A bunch of tiny CSS changes. Adjusts things like margins, saturation, tint, padding, etc. of various site components. Trying to make it look more polished.
> Try system fonts

- js/controllers/ModalViewController.js
- scss/modalView.scss
- scss/popover.scss
Basically:
1. Make animations feel snappier
2. Add blur
3. Move styling to .scss instead of in JavaScript files.
> Modify popovers

- js/controllers/ModalViewController.js
- scss/modalView.scss
> Animate backdrop

- .esdoc.json
- misc/markdown-renderer.js
- package.json
- scss/body.scss
- scss/body/figures.scss
- scss/body/headers.scss
Put images in figures i.e. add captiosn
> Add figures

- deploy/update.bash
- requirements.txt
> MySQL 8.0 upgrade requirements

- app/routes/answer.py
- js/models/Request/PublishEdit.js
> Fix publish post route

- app/controllers/comment.py
> Make so can't receive comments from self

- scss/fs-modal.scss
- scss/variables-dark.scss
Adjusts contrasts and color. Moves from blue to white as contrast to improve readability and aesthetics 
> Make dark theme less yuck

- app/notifications/apns.py
> Remove APNS device if token expired

- app/controllers/user_settings.py
- app/models/User.py
- app/routes/user.py
- app/routes/user_settings.py
- js/models/Request/ModifyUser.js
- js/models/Request/PrivacySettings.js
- js/template/NavigationTemplate.js
- js/template/ProfileSettings/ProfileSettingsViewPrivacy.js
- scss/form.scss
- scss/page/profile/profile.scss
- templates/user.html
Check button on user setting to show SE account on profile
> Add button to show SE on profile

- js/template/Form/SearchInputTemplate.js
- scss/search/picker.scss
Adjusts CSS on the dropdown-select input templates and also adds a state to show if more are not shown
Resolves #228
> Upgrade select input templates. Better styling etc

- app/controllers/admin.py
- app/controllers/auth.py
- app/models/User.py
- app/routes/admin.py
- app/routes/auth.py
- app/routes/user.py
- app/session/csrf.py
- app/session/user_session.py
Backend branch for additional admin tools (nuke user, merge users, reset votes)
Needs frontend on user page for nuke, merge, and reset votes
> more admin tools

- app/controllers/auth.py
- app/controllers/webapn.py
- app/helpers/oauth/profiles.py
- app/instances/csrf.py
- app/models/APNDevice.py
- app/models/Notification.py
- app/notifications/webapn.py
- app/notifications/webpush.py
- app/session/user_session.py
- package-lock.json
1. Fixes session id generation to be time-based
2. Removed M2Crypto replacing it with pyOpenSSL and pyca/Cryptography
3. Fix outdated Google OAuth by moving from G+ to Profile API
> Axtell Revival Update
